baseURL = 'https://ntc.beer/'
languageCode = 'en-us'
title = 'North Texas Homebrew Circuit'
theme = "tailbliss"

[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = false

[menus]
  [[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 10
  [[menus.main]]
  name = 'Competitions'
  pageRef = '/competitions'
  weight = 20

[[redirects]]
  from = "/"
  to = "/about"
  status = 301
  force = true