[build]
publish = "public"
command = """\
  npm install postcss-cli autoprefixer tailwindcss @tailwindcss/typography && \
  hugo --gc --minify \
  """

[context.production.environment]
HUGO_VERSION = "0.145.0"
NODE_VERSION = "22"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
